[package]
name = "whispact"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "whispact_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-blec = "0.5.2"
tauri-plugin-blep = { path = "../tauri-plugin-blep" }
tauri-plugin-nfc2 = { path = "../tauri-plugin-nfc2" }
anyhow = "1.0.97"
tokio = "1.44.2"
uuid = { version = "1.16.0", features = ["v4"] }
tauri-plugin-log = "2"
log = "0.4.27"
tauri-plugin-store = "2"
async-trait = "0.1.88"
tauri-plugin-fs = "2"

[target.'cfg(any(target_os = "android", target_os = "ios"))'.dependencies]
tauri-plugin-biometric = "2"
